### ISSUE TITLE
Decouple extracting from downloading?

### ISSUE THREAD

**Issue by bbelderbos** [rhelmstedter/eatlocal#1]
`download_bite` calls `extract_bite` yet latter is a separate cli option. So I think or `download_bite` should not call `extract_bite`, or `download_bite` should be renamed to `download_and_extract_bite` to make this explicit. 
I am writing a test working with the coupling for now.

**Comment by rhelmstedter** [comment]
I had the same thought. I think the best course is to separate them. After we see what Erik comes up with, maybe I can have the extraction as an optional flag. E.g., `eatlocal -d 1 -e 1`. I think the only concern will be to ensure the `download_bite` function runs before `extract_bite`.

**Comment by rhelmstedter** [comment]
This has been done in the code base, just not pushed to pypi yet.
