### ISSUE TITLE
Use 'q', 'Q', or 'esc' to exit display bite

### ISSUE THREAD

**Issue by rhelmstedter** [rhelmstedter/eatlocal#13]
Currently, the display bite command displays the instructions and the code for the bite in a `rich` layout object. It is displayed with `with Live(layout, screen=True):`. Then it asks for `input()`. This means you can close it with either press `enter` or `<Ctrl-C>`. It would be nice to be able to close the display with any of 'q', 'Q', or 'esc'.

**Comment by rhelmstedter** [comment]
This has been fixed with the most recent commit. Will push to pypi next.

**Comment by JnyJny** [comment]
Usually you put the commit in a comment, 188a0a7, and then GitHub will automatically hot-link it for us.
