### ISSUE TITLE
Some bites not downloading

### ISSUE THREAD

**Issue by Se7enSquared** [rhelmstedter/eatlocal#22]
I've had no issues for many bites. Now just today bite 257 and 270 failed to download. 262 successfully downloaded in between these two. 
![image](https://user-images.githubusercontent.com/30607353/162555970-29958a94-b7fc-463c-a3f6-d8b79aee745c.png)

**Comment by Se7enSquared** [comment]
Now I'm wondering if it's something to do with me. 278 would also not download today. Missing ZIP archive. :(

**Comment by Se7enSquared** [comment]
Workaround: Create the folder and files (named as they are named on the site) and they will submit properly when  you're done

**Comment by rhelmstedter** [comment]
I just attempted to download bite 257 and got the same thing. I copied the link address and saw the url pointing to the zip archive contains the wrong bite number, but downloads the correct bite. That looks like an issue that has to be fixed on @bbelderbos's end.

For now, manually downloading and keeping the naming convention should still let you submit via `eatlocal` until we can get it resolved. I'll message Bob in the slack and see how he wants to proceed/track the problematic bites.

Have you had any other bites that you are unable to download?

**Comment by bbelderbos** [comment]
Great catch, thanks @Se7enSquared. 

This was a bug with how the eatlocal endpoint on our platform tried to match the Bite object by the number provided.

It should work now as demonstrated below:

```
(venv) √ eatlocal (main) $ python -m eatlocal download 270
https://codechalleng.es/bites/api/eatlocal/270
Extracted bite 270 @ /Users/bbelderbos/code/eatlocal/270
(venv) √ eatlocal (main) $ lt 270
total 32
-rw-r--r--  1 bbelderbos  staff   387B Apr 12 14:58 README.md
-rw-r--r--  1 bbelderbos  staff   471B Apr 12 14:58 bite.html
-rw-r--r--  1 bbelderbos  staff    42B Apr 12 14:58 freq.py
-rw-r--r--  1 bbelderbos  staff   279B Apr 12 14:58 test_freq.py
```

**Comment by rhelmstedter** [comment]
Thanks @bbelderbos! I'm going to close this issue.

**Comment by bbelderbos** [comment]
Yw, let me know if any issues. I think it should all work as expected now (I tested quite a few). 
The only thing is for Newbie Bites you would use the id (primary key), not the Newbie Bite sequence number, did you try those?

**Comment by rhelmstedter** [comment]
I have never tried Newbie Bites with `eatlocal`. There isn't an option on the site to solve them offline. I just double checked and there is an option for the intro bites which are bites 101-110.

I think it makes sense to not worry about solving the newbie bites locally. Just the bites themselves are challenging enough let alone worrying about setting up chromedriver and learning git.

**Comment by bbelderbos** [comment]
OK thanks, then I think we're good, Intro Bites work with their ids:

```
$ python -m eatlocal download 109
https://codechalleng.es/bites/api/eatlocal/109
Extracted bite 109 @ /Users/bbelderbos/code/eatlocal/109
```
