### ISSUE TITLE
CRLF line terminators

### ISSUE THREAD

**Issue by bbelderbos** [rhelmstedter/eatlocal#3]
Upon downloading a Bite we get these:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/387927/150631652-75a14340-361a-463b-8690-2c72a3768874.png">

`:e ++ff=unix` in Vim reveals them (https://stackoverflow.com/a/27259548)

Not sure if this utility should nuke them or that's something we need to do pre-zip on our platform?

One user reported he was doing `perl -i -e 's/\r//' *.py` as extra step after download + extract.

**Comment by rhelmstedter** [comment]
I could not reproduce any error. As far as I know, `^M` is just a carriage return. When I added new lines, closed the file, and reopened in vim with `:e ++ff=unix` They were still appeared. Per our conversation, I don't think we need to worry about this. (I am about to close my first ever issue on GitHub exciting times).

**Comment by bbelderbos** [comment]
Thanks for confirming @rhelmstedter
